version: '3.8'

services:
  hello-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    volumes:
      - ./logs:/app/logs
    networks:
      - sbxservice-network

networks:
  sbxservice-network:
    driver: bridge 